fix style

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -76,7 +76,7 @@ jobs:
           make ui_deps
       - name: Check format
         run: |
-          pnpm prettier --check . || (echo "::error ::Please format your code by using 'yarn fmt'"; exit 1)
+          pnpm fmt-check || (echo "::error ::Please format your code by using 'pnpm fmt-fix'"; exit 1)
         working-directory: ui-new
       - name: Build UI
         run: |
