update Makefile and CI/CD

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -18,7 +18,7 @@ jobs:
         uses: actions/checkout@v3
       - uses: actions/setup-go@v3
         with:
-          go-version: "1.15"
+          go-version: '1.15'
       - name: Load go module cache
         uses: actions/cache@v3
         with:
@@ -48,23 +48,19 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
-      - uses: actions/setup-node@v3
+      # https://pnpm.io/continuous-integration#github-actions
+      - name: Setup PNPM
+        uses: pnpm/action-setup@v2.2.2
         with:
-          node-version: "16"
-      - name: Get yarn cache directory path
-        id: yarn-cache-dir-path
-        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
-        working-directory: ui
-      - uses: actions/cache@v3
-        id: yarn-cache
+          version: 7
+      - name: Setup Node.js
+        uses: actions/setup-node@v2
         with:
-          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
-          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
-          restore-keys: |
-            ${{ runner.os }}-yarn-
+          node-version: '16'
+          cache: 'pnpm'
       - uses: actions/setup-go@v3
         with:
-          go-version: "1.15"
+          go-version: '1.15'
       - name: Load go module cache
         uses: actions/cache@v3
         with:
@@ -74,13 +70,13 @@ jobs:
           key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
           restore-keys: |
             ${{ runner.os }}-go-
-      - name: Install yarn packages
+      - name: Install ui packages
         run: |
-          make yarn_dependencies
+          make ui_deps
       - name: Check format
         run: |
-          yarn prettier --check . || (echo "::error ::Please format your code by using 'yarn fmt'"; exit 1)
-        working-directory: ui
+          pnpm prettier --check . || (echo "::error ::Please format your code by using 'yarn fmt'"; exit 1)
+        working-directory: ui-new
       - name: Build UI
         run: |
           make ui
