fix CI

diff --git a/.github/workflows/pr-build.yaml b/.github/workflows/pr-build.yaml
--- a/.github/workflows/pr-build.yaml
+++ b/.github/workflows/pr-build.yaml
@@ -69,13 +69,13 @@ jobs:
         run: |
           yarn prettier --check . || (echo "::error ::Please format your code by using 'yarn fmt'"; exit 1)
         working-directory: ui
-      - name: Check type
-        run: |
-          yarn tsc || (echo "::error ::Please check your code type by using 'yarn tsc'"; exit 1)
-        working-directory: ui
       - name: Build UI
         run: |
           make ui
         env:
           NO_MINIMIZE: true
           CI: true
+      - name: Check type
+        run: |
+          yarn tsc || (echo "::error ::Please check your code type by using 'yarn tsc'"; exit 1)
+        working-directory: ui
