*: Add Prettier in CI (#282)
* *: Add prettier and hooks

Signed-off-by: Breezewish <me@breeswish.org>

* Force format everything

Signed-off-by: Breezewish <me@breeswish.org>

* Fix failure

Signed-off-by: Breezewish <me@breeswish.org>

diff --git a/.github/workflows/pr-build.yaml b/.github/workflows/pr-build.yaml
--- a/.github/workflows/pr-build.yaml
+++ b/.github/workflows/pr-build.yaml
@@ -65,6 +65,13 @@ jobs:
           key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
           restore-keys: |
             ${{ runner.os }}-go-
+      - name: Install yarn packages
+        run: |
+          make yarn_dependencies
+      - name: Check format
+        run: |
+          yarn prettier --check . || (echo "::error ::Please format your code using 'yarn format'"; exit 1)
+        working-directory: ui
       - name: Build UI
         run: |
           make ui
